language: objective-c
install: true
before_install:
    - brew update
    - brew install bazel
script:
    - bazel --batch test Tests --ios_minimum_os=9.1 --test_strategy=standalone --noshow_progress --noshow_loading_progress --verbose_failures --test_verbose_timeout_warnings --test_output=errors
